routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\Buku;
use App\Kategori;

// Route::filter('admin', function(){
// });

Route::get('/', function () {
  $categories = Kategori::with(['buku'=> function($q){
    $q->withCount('peminjaman');
  }])->get();
  return view('perpus_home', [
    'categories' => $categories
  ]);
})->name('home');

Auth::routes();
Route::get('/password/reset', 'UserController@show_reset_password')->name('password.request');

Route::get('/login', 'UserController@show_login')->name('login');
Route::post('/login', 'UserController@do_login');
Route::get('/logout', 'UserController@do_logout');
// Route::get('/home', 'HomeController@index')->name('home');


Route::get('/user/profile', 'UserController@profile');
Route::post('/user/{id}', 'UserController@update');

Route::group(['middleware'=>['admin']], function(){
  Route::resource('/admin/buku','BukuAdminController');
  Route::get('/admin/buku/{id}/delete','BukuAdminController@delete');
  Route::post('/admin/buku/{id}/edit', 'BukuAdminController@update');
  Route::resource('/admin/kategori','KategoriAdminController');
  Route::post('/admin/kategori/{id}/edit', 'KategoriAdminController@update');
  Route::get('/admin/kategori/{id}/delete','KategoriAdminController@delete');
  Route::resource('/admin/peminjaman','PeminjamanAdminController');
  Route::get('/admin/peminjaman/{id}/delete','PeminjamanAdminController@delete');
});


Route::resource('/buku', 'BukuController');
Route::resource('/kategori', 'KategoriController');
Route::resource('/tag', 'TagController');
Route::resource('/user', 'UserController');
Route::resource('/peminjaman', 'PeminjamanController');
Route::get('/peminjaman/{id}/create', 'PeminjamanController@create');
Route::get('/peminjaman/{id}/delete', 'PeminjamanController@delete');

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/perpus.blade.php
<!doctype html>
<html lang="en">
  <head>
    <title>Perpustakaan</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport" />

    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <!--     Fonts and icons     -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />

    <!-- Material Dashboard CSS -->
    <link rel="stylesheet" href="{{ asset('css/material-dashboard.min.css') }}" type="text/css">

  </head>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-12">
          <nav class="navbar navbar-expand-lg bg-rose">
            <div class="container-fluid">
                <div class="navbar-translate">
                    <a class="navbar-brand" href="/">Perpustakaan</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                        <span class="navbar-toggler-icon"></span>
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div>

                <div class="collapse navbar-collapse">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            <a href="{{ route('home') }}" class="nav-link">Home</a>
                        </li>
                        <li class="nav-item" style="text-transform:uppercase">
                          <div class="dropdown show">
                            <a class="nav-link dropdown-toggle" href="#" role="button" id="dropDownKategori" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              Kategori
                            </a>
                            <div class="dropdown-menu" aria-labelledby="dropDownKategori">
                              @foreach($categories as $category)
                                <a class="dropdown-item" href="{{ action('KategoriController@show', $category->id) }}">{{ $category->kategori }}</a>
                              @endforeach
                            </div>
                          </div>
                        </li>
                        <li class="nav-item">
                          @if(Auth::user())
                            <div class="dropdown show">
                              <a class="nav-link dropdown-toggle" href="#" role="button" id="dropDownUser" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {{ Auth::user()->name }}
                              </a>
                              <div class="dropdown-menu" aria-labelledby="dropDownUser">
                                <a class="dropdown-item" href="{{ action('UserController@profile') }}">Profile</a>
                                <a class="dropdown-item" href="{{ action('PeminjamanController@index') }}">Buku Dipinjam</a>
                                <a class="dropdown-item" href="{{ action('UserController@do_logout') }}">Logout</a>
                              </div>
                            </div>
                          @else
                            <div class="dropdown show">
                              <a class="nav-link dropdown-toggle" href="#" role="button" id="dropDownAuth" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Masuk
                              </a>
                              <div class="dropdown-menu" aria-labelledby="dropDownAuth">
                                <a class="dropdown-item" href="{{ action('UserController@show_login') }}">Login</a>
                                <a class="dropdown-item" href="{{ action('UserController@create') }}">Register</a>
                              </div>
                            </div>
                          @endif
                        </li>
                        @if(Auth::user() && (Auth::user()->type == 0))
                        <li class="nav-item">
                          <div class="dropdown show">
                            <a class="nav-link dropdown-toggle" href="#" role="button" id="dropDownAdmin" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              ADMIN
                            </a>
                            <div class="dropdown-menu" aria-labelledby="dropDownAdmin">
                              <a class="dropdown-item" href="{{ action('BukuAdminController@index') }}">Buku</a>
                              <a class="dropdown-item" href="{{ action('KategoriAdminController@index') }}">Kategori</a>
                              <a class="dropdown-item" href="{{ action('PeminjamanAdminController@index') }}">Peminjaman</a>
                            </div>
                          </div>
                        </li>
                        @endif
                    </ul>

                    <form class="form-inline ml-auto" method="GET" action="{{ action('BukuController@index') }}">
                        <div class="form-group has-white">
                          <input type="text" class="form-control" name="search" placeholder="Cari Buku">
                        </div>
                        <button type="submit" class="btn btn-white btn-raised btn-fab btn-fab-mini btn-round">
                            <i class="material-icons">search</i>
                        </button>
                    </form>
                </div>
            </div>
        </nav>
        </div> <!-- end column -->
      </div> <!-- end row -->
      @yield('content')
    </div> <!-- end container fluid -->

    <!--   Core JS Files   -->
    <script src="{{ asset('js/core/jquery.min.js') }}"></script>
    <script src="{{ asset('js/core/popper.min.js') }}"></script>
    <script src="{{ asset('js/bootstrap-material-design.js') }}"></script>

    <!-- Material Dashboard Core initialisations of plugins and Bootstrap Material Design Library -->
    <script src="{{ asset('js/plugins/perfect-scrollbar.jquery.min.js') }}"></script>
    <script src="{{ asset('js/material-dashboard.js?v=2.0.0') }}"></script>

    <script>
    $('document').ready(function(){
      $('.card-hover').hover(function(){
        $(this).find('.card-body').animate({
          'opacity': 1,
          'top': 200
        },200);
      },function(){
        $(this).find('.card-body').animate({
          'opacity': 0,
          'top': 210
        },200);
      });
    });
    </script>
  </body>
</html>

resources/views/perpus_home.blade.php
@extends('perpus')
@section('content')
  @foreach($categories as $category)
    @if(count($category->buku))
    <div class="alert alert-common">
      <h5 style="text-transform:uppercase; font-weight:bold">{{ $category->kategori }}</h5>
    </div>
    <div class="row">
      @foreach($category->buku as $book)
        <div class="col-3">
          <div class="card card-hover" style="width: 250px; margin-left:10px;margin-right:0; height:400px; position:relative">
            <img class="card-img-top" src="{{ asset('/images/'.$book->url_cover) }}" alt="Card image cap">
            <div class="card-body" style="position: absolute;top:210px; opacity:0; background-color:rgba(255,255,255,0.7);width:100%;height: 50%;bottom:0;color:#000">
              <h6 style="margin:0" class="card-title"><strong>{{ str_limit($book->judul, 40) }}</strong></h6>
              <p style="margin:0">Tersedia: {{ ($book->stock - $book->peminjaman_count) }}</p>
              <p class="card-text" style="font-size:0.8em">{{ str_limit($book->sinopsis, 100) }}</p>
            </div>
            <div style="width:100%;text-align:center;position:absolute;bottom:0;left:0">
              @if(($book->stock - $book->peminjaman_count) > 0)
                <a href="{{ action('BukuController@show', $book->id) }}" class="btn btn-primary">Lihat</a>
              @else
                <button class="btn btn-disabled">Habis</button>
              @endif
            </div>
          </div>
        </div>
      @endforeach
    </div>
  @endif
  @endforeach
@endsection